### ISSUE TITLE
Addon fails to start with "Login failed with reason: Bad credentials"

### ISSUE THREAD

**Issue by Pomezny** [hassio-addons/addon-spotify-connect#267]
# Problem/Motivation

> Addon fails to start, spotifyd crashes. Error "[2024-08-14T09:25:51Z ERROR librespot] Connection failed: Login failed with reason: Bad credentials" can be observed in the log.

## Expected behavior

> Start the addon

## Actual behavior

> Main process crashes.

## Steps to reproduce

> Add Spotify username and Spotify password to the config and try to run the addon

## Proposed changes

> This issue is filed only to let other users and maintainer know what is going on. Spotify recently disabled username/password access which librespot uses as an authentication method to for the API. Workaround might me removing credentials, but it was observed that device discovery might not work. 
> Proper solution in this repository is probably not possible, since it relies on librespot and we need to wait for the librespot team to resolve this issue. There already is issue in their repository and its looks like they are already working on solution here https://github.com/librespot-org/librespot/issues/1308 
> When librespot comes up with the solution addon will probably need some changes and update to latest librespot

**Comment by rakalex** [comment]
same issue, after upgraded to the latest HA Os version.

**Comment by tjorim** [comment]
Spotify disabled the use of username/password last weekend. We can't do anything about it at the moment as we rely on librespot. I can't test right now but the issue should only be auth. If starting without a username/password, it should still be discovered on your local network.

**Comment by rosicenko** [comment]
Yep, same happened to Music Assistant but there it is already fixed.

**Comment by Rolfvanderplas** [comment]
Yep, same for me.  Starting without username/password suceeded.

**Comment by dtap001** [comment]
same here. please fix it

**Comment by CountOlaf87** [comment]
I'm having the same issue here

**Comment by mwarchulinski** [comment]
Same here. I tried to change my password, add a new connection method to my spotify account and even reinstall the addon. I'm starting to dig around librespot now.

**Comment by gungam** [comment]
same here
tried Music Assistant:
> Yep, same happened to Music Assistant but there it is already fixed.
but I'm unable to figure out to use the local audio out of the pi...
It seems to support only streaming devices as chrome cast oder sonos...

**Comment by ironcrafter54** [comment]
> but I'm unable to figure out to use the local audio out of the pi... :-(
> It seems to support only streaming devices as chrome cast oder sonos...

FYI I have found the best way to get audio out of the pi, assuming you are running HA is to install the shairport sync addon using this repository https://github.com/v3rm0n/hassio
yes it is unmaintained, but for now it still works well, then add airplay as a player in Music assistant and It should automatically discover the shairport sync addon.

**Comment by PerSterin** [comment]
Yep, same for me. Starting without username/password suceeded. Debug logs without username and password and with username and password below. Have reinstalled Add-on: Spotify Connect, and changed the password.

Without username/password.
-----------------------------------------------------------
 Add-on: Spotify Connect
 Play Spotify music on your Home Assistant device
-----------------------------------------------------------
 Add-on version: 0.13.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.8.3
 Home Assistant Supervisor: 2024.08.0
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to DEBUG
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun spotifyd (no readiness notification)
[23:24:02] INFO: Starting the Spotify daemon...
s6-rc: info: service legacy-services successfully started
[2024-08-25T21:24:02Z INFO  librespot] librespot 0.4.2 UNKNOWN (Built on 2024-01-06, Build ID: 8ZfE3H9w, Profile: release)
[2024-08-25T21:24:02Z TRACE librespot] Command line argument(s):
[2024-08-25T21:24:02Z TRACE librespot] 		bitrate "320"
[2024-08-25T21:24:02Z TRACE librespot] 		name "Spotify"
[2024-08-25T21:24:02Z TRACE librespot] 		disable-audio-cache
[2024-08-25T21:24:02Z TRACE librespot] 		verbose
[2024-08-25T21:24:02Z DEBUG librespot_discovery::server] Zeroconf server listening on 0.0.0.0:36319


With username/password.
-----------------------------------------------------------
 Add-on: Spotify Connect
 Play Spotify music on your Home Assistant device
-----------------------------------------------------------
 Add-on version: 0.13.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 13.0  (amd64 / generic-x86-64)
 Home Assistant Core: 2024.8.3
 Home Assistant Supervisor: 2024.08.0
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
Log level is set to DEBUG
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun spotifyd (no readiness notification)
[23:29:49] INFO: Starting the Spotify daemon...
s6-rc: info: service legacy-services successfully started
[2024-08-25T21:29:49Z INFO  librespot] librespot 0.4.2 UNKNOWN (Built on 2024-01-06, Build ID: 8ZfE3H9w, Profile: release)
[2024-08-25T21:29:49Z TRACE librespot] Command line argument(s):
[2024-08-25T21:29:49Z TRACE librespot] 		bitrate "320"
[2024-08-25T21:29:49Z TRACE librespot] 		name "Spotify"
[2024-08-25T21:29:49Z TRACE librespot] 		username "XXXXXXXX"
[2024-08-25T21:29:49Z TRACE librespot] 		password "XXXXXXXX"
[2024-08-25T21:29:49Z TRACE librespot] 		disable-audio-cache
[2024-08-25T21:29:49Z TRACE librespot] 		verbose
[2024-08-25T21:29:49Z DEBUG librespot_discovery::server] Zeroconf server listening on 0.0.0.0:40565
[2024-08-25T21:29:49Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:4070
[2024-08-25T21:29:49Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:443
[2024-08-25T21:29:49Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gew4.spotify.com:80
[2024-08-25T21:29:49Z WARN  librespot_core::apresolve] Ignoring blacklisted access point ap-gue1.spotify.com:4070
[2024-08-25T21:29:49Z INFO  librespot_core::session] Connecting to AP "ap-gew1.spotify.com:443"
[2024-08-25T21:29:50Z ERROR librespot] Connection failed: Login failed with reason: Bad credentials
[23:29:50] WARNING: spotifyd crashed, halting add-on
s6-rc: info: service legacy-services: stopping
[23:29:50] INFO: spotifyd stoped, restarting...
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

**Comment by Goodie01** [comment]
After removing my username/password (best done through the "Edit in YAML" option) it seems to work as expected. Maybe with a slow initial connection?

**Comment by MaxValue** [comment]
Meta Info for anyone following this:

- [librespot issue which is the upstream source of the incident: 1308](https://github.com/librespot-org/librespot/issues/1308) which is fixed by the [librespot pull request which is not yet merged: 1309](https://github.com/librespot-org/librespot/pull/1309)
- [Music Assistant Issue with the same problem: 2749](https://github.com/music-assistant/hass-music-assistant/issues/2749) which seems to be fixed by the [Music Assistant pull request 1562](https://github.com/music-assistant/server/pull/1562) (which was never linked, but @OzGav and @marcelveldt never linked them together before locking the discussion, so it was a bit a PITA to find this)

**Comment by brixharlem** [comment]
Has anybody found a workaround yet? Spotify Connect works after removing username and password, but I always need another device (e.g. smartphone) to "authenticate" Home Assistant by handing over the speaker. After HA restart, it has to be repeated. Thank you!

**Comment by robertjscooper** [comment]
For referenece; [librespot](https://github.com/librespot-org/librespot) has now merged a [PR](https://github.com/librespot-org/librespot/pull/1309) for handling OAuth2.0 authentication.

**Comment by fchaudhri02** [comment]
Is there any update on this? I was using this at my business to automatically play music locally on home assistant which was connected to an AV receiver. Eagerly waiting for this to be fixed.

**Comment by brixharlem** [comment]
@fchaudhri02 I finally bought an audiocast device. This fixed it for me and works much better than before.

**Comment by fchaudhri02** [comment]
> @fchaudhri02 I finally bought an audiocast pro device. This fixed it for me and works much better than before.

@brixharlem How are you using that with home assistant? Are you using Spotify or Spotify Plus integration?

I had purchased WiiM Mini to try. My theory was if I put WiiM and home assistant on the same network, I should see WiiM as a device on the Spotify integration and should be able to play to it. If that worked, all of my automation should work, but Spotify integration doesn't see the WiiM. However, I am able to play to WiiM from the phone app.

**Comment by brixharlem** [comment]
> > @fchaudhri02 I finally bought an audiocast pro device. This fixed it for me and works much better than before.
> 
> @brixharlem How are you using that with home assistant? Are you using Spotify or Spotify Plus integration?
> 
> I had purchased WiiM Mini to try. My theory was if I put WiiM and home assistant on the same network, I should see WiiM as a device on the Spotify integration and should be able to play to it. If that worked, all of my automation should work, but Spotify integration doesn't see the WiiM. However, I am able to play to WiiM from the phone app.

Both works fine. After connecting, the "source" is available and never disappeared. The device is running for a week.

**Comment by fchaudhri02** [comment]
> > > @fchaudhri02 I finally bought an audiocast pro device. This fixed it for me and works much better than before.
> > 
> > 
> > @brixharlem How are you using that with home assistant? Are you using Spotify or Spotify Plus integration?
> > I had purchased WiiM Mini to try. My theory was if I put WiiM and home assistant on the same network, I should see WiiM as a device on the Spotify integration and should be able to play to it. If that worked, all of my automation should work, but Spotify integration doesn't see the WiiM. However, I am able to play to WiiM from the phone app.
> 
> Both works fine. After connecting, the "source" is available and never disappeared. The device is running for a week.

@brixharlem Would you be able to share the steps you took to get it working? I can't figure out what am I missing or doing wrong. 

For me, the spotify integration doesn't see Audiocast pro device. However, the spotifyplus integration does see it, but it fails to play on it. It gives me an error about credentials.

**Comment by brixharlem** [comment]
@fchaudhri02 Have you initialized the Spotify connection to Audiocast once with your mobile? Is the device available in the Spotify app?

**Comment by realGlorix** [comment]
> After removing my username/password (best done through the "Edit in YAML" option) it seems to work as expected. Maybe with a slow initial connection?

thank you so much.

**Comment by gungam** [comment]
Push

**Comment by mwarchulinski** [comment]
Waiting for the plugin update. librespot has a new version where the issue seems to be fixed.

**Comment by SteeledKnight** [comment]
Still an active issue. A new release needs to be published with the latest version of librespot

**Comment by brixharlem** [comment]
> Still an active issue. A new release needs to be published with the latest version of librespot

Especially, because using the credentials in the current settings is causing a Spotify password reset.

**Comment by joshschmelzle** [comment]
Also looking for this to be fixed. Thanks! :)

**Comment by StrohhutGit** [comment]
Also still not works for me :(

**Comment by Mooseral** [comment]
Please release the new version as soon as possible, this is an ongoing problem that prevents usage of the add-on! I'm planning to make a donation if the release comes out before I need to buy hardware to resolve my Spotify streaming situation...

**Comment by StrohhutGit** [comment]
I found a very good alternativ Solution —> [Spotifyd](https://github.com/Spotifyd/spotifyd). I tested some other but this one is very good

**Comment by Mooseral** [comment]
> I found a very good alternativ Solution —> [Spotifyd](https://github.com/Spotifyd/spotifyd). I tested some other but this one is very good

Looking at Spotifyd, it looks like they have open issues around credentials as well? Also, it isn't set up to be installed via Hass.io; I could set up another Raspberry Pi just as a Spotify Connect device, or mess around with installing into the hass.io host directly, but I'd rather do neither of these (especially with this add-on appearing to have implemented newer package versions that should fix the issues on its main branch already...)

Thanks for the recommendation though! I will consider it moving forward.

**Comment by StrohhutGit** [comment]
> > I found a very good alternativ Solution —> [Spotifyd](https://github.com/Spotifyd/spotifyd). I tested some other but this one is very good
> 
> Looking at Spotifyd, it looks like they have open issues around credentials as well? Also, it isn't set up to be installed via Hass.io; I could set up another Raspberry Pi just as a Spotify Connect device, or mess around with installing into the hass.io host directly, but I'd rather do neither of these (especially with this add-on appearing to have implemented newer package versions that should fix the issues on its main branch already...)
> 
> Thanks for the recommendation though! I will consider it moving forward.

Yes you need annother Device or like me a Proxmox. Sorry forgot to mention that. 

I am using Spotifyd for 2 weeks now and I had no Problems until now. I also dont need any credentials for my Premium Spotfy Account. So there are no Problems with the credentials in the First Place. Spotfiyd is working like a receiver with onboard spotify connect. 

But I understand why you dont want to go that way. But keep it in mind. Maybe you will do it someday :)

**Comment by frenck** [comment]
Please check: https://github.com/hassio-addons/addon-spotify-connect/releases/tag/v0.14.0

**Comment by Fibbis** [comment]
> Please check: https://github.com/hassio-addons/addon-spotify-connect/releases/tag/v0.14.0

It still fails but now the logs gives a new error message.

Invalid `--password` / `-p`: Password authentication no longer supported, use OAuth

I can’t seem to find how to use oauth. Can someone please explain it to me?

**Comment by StrohhutGit** [comment]
> > Please check: https://github.com/hassio-addons/addon-spotify-connect/releases/tag/v0.14.0
> 
> It still fails but now the logs gives a new error message.
> 
> Invalid `--password` / `-p`: Password authentication no longer supported, use OAuth
> 
> I can’t seem to find how to use oauth. Can someone please explain it to me?

I have the same error

**Comment by RymenTe** [comment]
I still have the same Problem: 
2025-02-16T20:53:48Z INFO  librespot_core::session] Connecting to AP "ap-guc3.spotify.com:4070"
[2025-02-16T20:53:48Z ERROR librespot] Connection failed: Login failed with reason: Bad credentials

I also have intsalled the following Integrations that use Spotify Auth: Spotcast, Spotify Offical Integration, Music Assistant 

I want this integration to launch music on my Sever , to play music through the external Sever Speakers. Thanks for Help :)

**Comment by Kasandra-M** [comment]
> Looking into this, I think it isn't realistic to keep authentication around. OAuth can potentially be added, but it would be very shitty experience to use and set up.
> 
> IMHO that juice isn't worth the squeeze.

OAuth2 doesn't have to be hard for the end user, and let's be honest most HA configurations aren't exactly one click setup. Having looked at the spotify oauth2 documentation briefly, it seems to work pretty similar to Microsoft's, so it should at worst require a local DNS or /etc/hosts entry for home assistant's IP to serve as the basis of the redirect URI.

**Comment by StrohhutGit** [comment]
Maybe I am the only one but I don't know exactly what I have to do to get that Addon up running again. Or perhaps I missed some info. When I type in my credentials it obviously is not working and tells me to use OAuth. But how do I use it? The description of the addon is no updated. Maybe someone can point me in the right direction?
